before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
bundler_args: --without development production --quiet
before_install:
  - echo "yes" | gem uninstall json
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - "export DISPLAY=:99.0"
  - "bundle exec rspec spec"
notifications:
  email:
    - ryan@spreecommerce.com
<<<<<<< HEAD
branches:
  only:
    - 1-2-stable
    - master
=======
>>>>>>> 8e592a04a8e6123ac493c053875c78be6e197f8c
rvm:
  - 1.9.3
